### PR TITLE
Added knowledge list

### PR DESCRIPTION
**Pull request by RichardLitt**
Rather than link to a few random ones and have people PR each list (I wanted to add mine), I was thinking it might be easier to have a centralized, simple list of these repos. What do you think?

### CODE REVIEW

**Comment by theatlasroom** [comment]
@RichardLitt that sounds like a good plan, my only suggestion would be maybe if the repo sat under @yoshuawuyts 's account since his seems to be the original we've all based from.

**Comment by RichardLitt** [comment]
I'd be happy to do that. @yoshuawuyts: want me to transfer ownership?

**Comment by RichardLitt** [comment]
@theatlasroom Added Yoshua's name at the top. See https://twitter.com/yoshuawuyts/status/822238455535124481. :)

**Comment by theatlasroom** [comment]
Bam!

**Comment by RichardLitt** [comment]
Bam! Thanks.

**Pull request merged**
